const IMGS = {
  coilovers: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=160&h=160&fit=crop&auto=format",
  turbo: "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=160&h=160&fit=crop&auto=format",
  intercooler: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=160&h=160&fit=crop&auto=format",
  exhaust: "https://images.unsplash.com/photo-1611016186353-9af58c69a533?w=160&h=160&fit=crop&auto=format",
  brakes: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=160&h=160&fit=crop&auto=format",
  engine: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=160&h=160&fit=crop&auto=format",
  bov: "https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=160&h=160&fit=crop&auto=format",
  lsd: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=160&h=160&fit=crop&auto=format",
  intake: "https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=160&h=160&fit=crop&auto=format",
};

const DB = [
  { title: "HKS Coilover Suspension Kit — Nissan Silvia S14/S15", source: "Deep Performance", type: "new", featured: true, price: 3200, loc: "Dubai", img: IMGS.coilovers, tags: ["coilovers","s14","s15","nissan","suspension","hks"], url: "https://deepperformance.ae" },
  { title: "BC Racing BR Series Coilovers — S14 240SX", source: "Intraco", type: "new", featured: false, price: 2750, loc: "Sharjah", img: IMGS.coilovers, tags: ["coilovers","s14","240sx","suspension","bc racing"], url: "https://intracotrading.com" },
  { title: "Used — S15 Silvia Coilovers (good condition)", source: "Dubizzle", type: "used", featured: false, price: 850, loc: "Dubai", img: IMGS.coilovers, tags: ["coilovers","s15","used","suspension"], url: "https://dubizzle.com" },
  { title: "Tein Flex Z Coilovers — Nissan 200SX S14", source: "Facebook Marketplace", type: "used", featured: false, price: 1400, loc: "Abu Dhabi", img: IMGS.coilovers, tags: ["coilovers","s14","200sx","tein","suspension"], url: "https://facebook.com/marketplace" },
  { title: "PSR Single Turbo Upgrade Kit — RB25", source: "FMIC UAE", type: "new", featured: true, price: 6800, loc: "Dubai", img: IMGS.turbo, tags: ["turbo","psr","rb25","single turbo","kit"], url: "https://fmicuae.com" },
  { title: "Turbonetics T3/T4 Turbocharger — RB25DET", source: "Deep Performance", type: "new", featured: false, price: 4100, loc: "Dubai", img: IMGS.turbo, tags: ["turbo","rb25","rb25det","turbonetics"], url: "https://deepperformance.ae" },
  { title: "HKS GT2530 Turbocharger — SR20DET", source: "YP Performance", type: "new", featured: false, price: 3800, loc: "Dubai", img: IMGS.turbo, tags: ["turbo","sr20","sr20det","hks","gt2530"], url: "https://yperformance1.com" },
  { title: "HKS SSQV Blow Off Valve — universal", source: "YP Performance", type: "new", featured: false, price: 620, loc: "Dubai", img: IMGS.bov, tags: ["bov","blow off","hks","ssqv"], url: "https://yperformance1.com" },
  { title: "Used — Greddy Blow Off Valve type RS", source: "Facebook Marketplace", type: "used", featured: false, price: 280, loc: "Dubai", img: IMGS.bov, tags: ["bov","blow off","greddy","used"], url: "https://facebook.com/marketplace" },
  { title: "Trust Greddy Intercooler Kit — RB25DET", source: "FMIC UAE", type: "new", featured: true, price: 2900, loc: "Dubai", img: IMGS.intercooler, tags: ["intercooler","fmic","rb25","rb25det","trust","greddy"], url: "https://fmicuae.com" },
  { title: "Mishimoto FMIC — 600x300 universal", source: "Atomic Shop", type: "new", featured: false, price: 1850, loc: "Sharjah", img: IMGS.intercooler, tags: ["intercooler","fmic","mishimoto","front mount"], url: "https://atomic-shop.ae" },
  { title: "Used — R32 GTR Front Mount Intercooler", source: "Dubizzle", type: "used", featured: false, price: 700, loc: "Sharjah", img: IMGS.intercooler, tags: ["intercooler","fmic","r32","gtr","used"], url: "https://dubizzle.com" },
  { title: "RB25DET Neo Engine — pulled, good compression", source: "Dubizzle", type: "used", featured: false, price: 6200, loc: "Dubai", img: IMGS.engine, tags: ["rb25","rb25det","neo","engine","used","swap"], url: "https://dubizzle.com" },
  { title: "SR20DET Engine — complete swap, 150k km", source: "Facebook Marketplace", type: "used", featured: false, price: 4500, loc: "Dubai", img: IMGS.engine, tags: ["sr20","sr20det","engine","swap","used"], url: "https://facebook.com/marketplace" },
  { title: "Brembo GT Big Brake Kit — front 4-pot S14", source: "Deep Performance", type: "new", featured: false, price: 7400, loc: "Dubai", img: IMGS.brakes, tags: ["brakes","brembo","big brake","s14","bbk"], url: "https://deepperformance.ae" },
  { title: "K-Sport 6-pot Big Brake Kit — 330mm rotor", source: "Intraco", type: "new", featured: false, price: 4100, loc: "Sharjah", img: IMGS.brakes, tags: ["brakes","ksport","big brake","bbk"], url: "https://intracotrading.com" },
  { title: "Tomei Expreme Ti Exhaust — Nissan Silvia S15", source: "YP Performance", type: "new", featured: false, price: 3300, loc: "Dubai", img: IMGS.exhaust, tags: ["exhaust","tomei","expreme","s15","titanium"], url: "https://yperformance1.com" },
  { title: "Used — HKS Hi-Power Exhaust S14, full system", source: "Dubizzle", type: "used", featured: false, price: 900, loc: "Dubai", img: IMGS.exhaust, tags: ["exhaust","hks","s14","used"], url: "https://dubizzle.com" },
  { title: "Nismo LSD — R200 Differential S14/S15", source: "Bin Jumah", type: "new", featured: true, price: 5200, loc: "Dubai", img: IMGS.lsd, tags: ["lsd","differential","nismo","r200","s14","s15"], url: "https://binjumah.com" },
  { title: "HKS Super Power Flow Intake — SR20/RB25", source: "Atomic Shop", type: "new", featured: false, price: 480, loc: "Sharjah", img: IMGS.intake, tags: ["intake","air filter","hks","sr20","rb25","induction"], url: "https://atomic-shop.ae" },
  { title: "Used — Nismo Cold Air Intake S14", source: "Facebook Marketplace", type: "used", featured: false, price: 220, loc: "Dubai", img: IMGS.intake, tags: ["intake","cold air","nismo","s14","used"], url: "https://facebook.com/marketplace" },
];
